### ISSUE TITLE
to_primitive/to_native

### ISSUE THREAD

**Issue by abhinav** [uber/thriftrw-python#14]
We should implement `to_primitive` and `to_native` methods akin to schematics.

`to_primitive` would convert arbitrary Thrift objects into JSON-able primitive types (dictionaries, lists, numerals, and strings), and `to_native` would be a class method to convert them back into an instance.

**Comment by abhinav** [comment]
@breerly

**Comment by abhinav** [comment]
## Proposal

Classes for generated types will have the following new methods:

- `to_primitive`: Converts the value into a primitive value. A primitive value is a text, integer, float, or a list or dict of other primitives.
- `to_native` (classmethod): Converts a primitive value into a value of the class.

### Example

```python
foo = thriftrw.load('foo.thrift')

a = foo.Bar(x='hello')
a.to_primitive()  # => {'x': 'hello'}

b = foo.Bar.to_native({'x': 'hello'})
a == b  # => True
```

### Implementation notes

`TypeSpec` will be augmented with `to_primitive` and `to_native` methods that mirror the behavior of `to_wire` and `from_wire` except that instead of working with wire values, they will work with primitive types. Generated classes will simply call the corresponding `to_primitive/native` for `Struct/Union/ExceptionTypeSpec`.

### Open questions

- How should `binary` values be treated? Should `binary` be another valid primitive type? Or should we simply convert all `bytes` into `unicode`? That is flimsy because fields that represent truly arbitrary binary blobs will fail to convert to unicode for certain inputs, so it would require some sort of annotation to say that 'this field is an arbitrary binary blob and should be base64 encoded for its primitive representation'.

---

Thoughts? CC @blampe @breerly @junchaowu

**Comment by breerly** [comment]
I like the design, with the primitive and native serialization methods living next to the wire serialization methods. Have you given thought to whether this API lends itself to scriptability? For example, could I iterate through a response and wake it up? Looks like `to_native` being a classmethod makes that difficult.

**Comment by junchaowu** [comment]
1. can we have a pair to_primitive/from_primitive ?  Just from the meaning to_primitive and to_native , it's not clear to know to_native means to convert to class.
2. for the binary thing, we need to be careful fro the unicode encode or decode. I'd leave the encode or decode to the customer.

**Comment by breerly** [comment]
@junchaowu how do you mean leave it up to the customer? Because these things are recursive in nature, we need to know what to do when we come across a binary. Perhaps annotations could help...

**Comment by abhinav** [comment]
> 1. can we have a pair to_primitive/from_primitive ? Just from the meaning to_primitive and to_native , it's not clear to know to_native means to convert to class.

I buy that. I would be willing to call this that or even something else if `primitive` is too long.

> 2. for the binary thing, we need to be careful fro the unicode encode or decode. I'd leave the encode or decode to the customer.

That's why it's an open question. We can't just leave it to the customer, though. In using the Thrift types we generate, the customer expects to not have to worry about encoding/decoding UTF-8. That's the point of the separation between `string` and `binary` types. The question really is about whether `binary` should be treated as a primitive or not.

**Comment by abhinav** [comment]
For example, under normal usage scenario, customers will expect this:

    union X { 1: string s; 2: binary b }

```python
X(s=u'foo')
X(b=b'\x00\x00')
```

But with `to_primitive`,

```python
X(s=u'foo')       # => {u's': u'foo'}
X(b=b'\x00\x00')  # => {u'b': ???}
```

So the question is, should `???` be `b'\x00\x00'`, `unicode(b'\x00\x00'`)`, or `u'AAA='` (base64 encoded).

**Comment by junchaowu** [comment]
@breerly when you just do unicode encode/decode, the binary stuff may not be converted to original one. based64 will help though. So there is question what kind of default encode do we want.

**Comment by abhinav** [comment]
We can't always base64 either. `binary` is also used in many places to indicate that the value is ASCII text. We can't just make that an unreadable base64 blob.

**Comment by abhinav** [comment]
Basically, I'm inclined to include binary as its own primitive type. This will push the responsibility of handling binary on the serialization library.

Example:

```
In [6]: print json.dumps({u's': u'foo', u'b': b'\x00\x00'})
{"s": "foo", "b": "\u0000\u0000"}

In [7]: print yaml.dump({u's': u'foo', u'b': b'\x00\x00'})
{!!python/unicode 'b': "\0\0", !!python/unicode 's': !!python/unicode 'foo'}

In [8]: print yaml.dump({u's': u'foo', u'b': b'\x00\x00'}, Dumper=yaml.SafeDumper)
{b: "\0\0", s: foo}
```

**Comment by breerly** [comment]
+1

**Comment by blampe** [comment]
+1 let's not b64 anything. Leave it up to serialization.
