### ISSUE TITLE
Message envelopes

### ISSUE THREAD

**Issue by abhinav** [uber/thriftrw-python#15]
This isn't needed for TChannel, but Thrift actually wraps requests and responses in a message envelope with the following attributes:

* `name`: Name of the method being called.
* `type`: Type of the message. This is one of `call` (1), `reply` (2), `exception` (3), and `oneway` (4).
* `seqid`: A 32-bit integer used by the client to match responses to requests if they support interleaved requests and responses. The server's contract is to return the same seqid in the response that it got in the request.
* `body`: The actual request/response struct/union.

For binary protocol, that uses the following format:

    name~4 type:1 seqid:4 body

Where body is just laid out as-is.

We should implement some sort of API for this so that thriftrw can be used for HTTP clients as well.

Worth noting that the binary protocol also has a strict version of the message wrapper:

    versionAndType:4 name~4 seqid:4 body
    versionAndType = version:2 0x00 type:1
    version = 0x8001

For reads, we probably want to support both, the strict and non-strict version. For writes, we can probably just pick one and roll with it.

**Comment by abhinav** [comment]
Proposed API:

## Client-side

```python

import thriftrw

keyvalue = thriftrw.load('keyvalue.thrift')
KeyValue = keyvalue.KeyValue

request_payload = keyvalue.dumps.message(
    KeyValue.getValue.request('foo'),
    id=42,  # optional -- will default to 0 if the client doesn't care
)
response_payload = send_request_to_server(request_payload)

# The message contains the name of the method and whether it's a CALL or REPLY,
# so we know exactly which method's request/response in KeyValue should be parsed.
reply_message = keyvalue.loads.message(KeyValue, response_payload)
# If the message contained an EXCEPTION (not an application exception), it will be
# raised.

print reply_message.body.success
# reply_message.body contains the response union. So, .success contains the
# actual return value.
```


## Server-side

```python
import thriftrw

keyvalue = thriftrw.load('keyvalue.thrift')
KeyValue = keyvalue.KeyValue


def request_handler(request):
    request_payload = request.body
    call_message = keyvalue.loads.message(KeyValue, request_payload)

    try:
        return_value = dispatch(call_message.name, call_message.body)
        # Dispatch to the appropriate method with the method arguments.
        # Build a KeyValue.getValue.response(success=..) object with the
        # result.
    except Exception:
        # Match exceptions against method exceptions and construct a
        # KeyValue.getValue.response() object.
        raise NotImplementError

    response = # The response union built above
    response_payload = keyvalue.dumps.message(response)
    return response_payload
```

## Open questions

- When parsing REPLY messages, the current plan says that the message body is the response union. Do we want it to be the return value instead? If we do that, we can raise an exception if the response union contained an application exception instead of the return value. This is more in line with what people expect from client libraries than serialization libraries.

**Comment by blampe** [comment]
So if `reply_message.body` is a union of the response type or exceptions, I'd say it'd be more "pythonic" to raise an exceptions and just return the response type as `reply_message.body.body`. That also feels more similar to what we're already doing in tchannel.

**Comment by abhinav** [comment]
Do you mean just `reply_message.body` instead of `reply_message.body.success`?

Also, does that mean we want to do something similar on the server side as well? Take a callable that returns the result or throws an application exception and translate that to a response union?

Will this not add a little inconsistency? The exception-unwrapping behavior will happen only when parsing messages, but the exception-wrapping behavior will happen when constructing response unions (using whatever API we decide) regardless of whether a message is being built or not.

**Comment by abhinav** [comment]
Okay, we decided that the more sophisticated server-side or client-side APIs can be built on top and the immediate concern/v1 of this feature should concern itself with serialization and deserialization only.
