### ISSUE TITLE
Generated classes to have reference to module for dumps/loads/etc...

### ISSUE THREAD

**Issue by abhinav** [uber/thriftrw-python#22]
Integrations that pass around just response objects, we'll need to assign a reference to the `__thrift_module__` such that the response objects can call `__thrift_module__.dumps` or `__thrift_module__.loads`.

**Comment by breerly** [comment]
@abhinav this still relevant?

**Comment by abhinav** [comment]
Yes, it allows users to easily convert a Thrift value into a serialized blob. There may be an alternative solution where users directly pass the protocol in. Let's leave this open until we decide on a solution.

**Comment by abhinav** [comment]
Not relevant anymore. Will reopen if need arises.

**Comment by breerly** [comment]
I'll be adding this to the generated request object.

**Comment by abhinav** [comment]
Merged into master
